v0.5.4 - gpu-check不发送显卡错误信息

diff --git a/bin/gpu-check b/bin/gpu-check
--- a/bin/gpu-check
+++ b/bin/gpu-check
@@ -154,13 +154,13 @@ if [[ "$1" == "list" || "$1" == "listjson" ]]; then
 					msg+="GPU ${gpubusid#00000000:} $gpuname - $statusmsg ($status)"$'\n'
 				done < <( echo "$NVIDIA_DATA" | grep -v "^0;" )
 
-				if [[ ! -z "$msg" ]]; then
-					# echo "$msg" >&2
-					say-message error "Nvidia GPU error" --payload=$msg > /dev/null
-				elif [[ $exitcode -ne 0 ]]; then
-					# echo "nvtool error ($exitcode)" >&2
-					say-message error "nvtool error ($exitcode)" --payload=$NVIDIA_DATA > /dev/null
-				fi
+				# if [[ ! -z "$msg" ]]; then
+				# 	# echo "$msg" >&2
+				# 	say-message error "Nvidia GPU error" --payload=$msg > /dev/null
+				# elif [[ $exitcode -ne 0 ]]; then
+				# 	# echo "nvtool error ($exitcode)" >&2
+				# 	say-message error "nvtool error ($exitcode)" --payload=$NVIDIA_DATA > /dev/null
+				# fi
 			fi
 
             ## Change 666666
